#define SCREEN_WIDTH 1280 
#define SCREEN_HEIGHT 720

#define PIXELS_PER_UNIT 10

#define SCREEN_CENTER_X (SCREEN_WIDTH / PIXELS_PER_UNIT / 2)
#define SCREEN_CENTER_Y (SCREEN_HEIGHT / PIXELS_PER_UNIT / 2)

#define FRICTION_COEF 0.95
#define GRAVITY 75